apiVersion: apps/v1
kind: Deployment
metadata:
  name: rev-hire-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rev-hire-app
  template:
    metadata:
      labels:
        app: rev-hire-app
    spec:
      containers:
      - name: rev-hire-container
        image: revature_hiring_application:latest
        ports:
        - containerPort: 4200
---
apiVersion: v1
kind: Service
metadata:
  name: rev-hire-service
spec:
  selector:
    app: rev-hire-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4200
  type: NodePort
